@api = http://localhost:8000

###
GET {{api}}/

###
GET {{api}}/healthz

###
POST {{api}}/auth/register

###
POST {{api}}/auth/login

###
GET {{api}}/users/all

###
GET {{api}}/users/{id}

###
PUT {{api}}/users/{id}

###
PATCH {{api}}/users/{id}/status

###
PATCH {{api}}/users/{id}/password

###
DELETE {{api}}/users/{id}
