@api = http://localhost:8000

###
GET {{api}}/

###
GET {{api}}/health

###
POST {{api}}/auth/register

{
    "email": "asd@gmail.com",
    "password": "asdasd"
}

###
POST {{api}}/auth/login

###
GET {{api}}/users/all

###
GET {{api}}/users/{id}

###
PUT {{api}}/users/{id}

###
PATCH {{api}}/users/{id}/status

###
PATCH {{api}}/users/{id}/password

###
DELETE {{api}}/users/{id}
