@api = http://localhost:8000

### admin
@id_admin = e991d113-58dc-414c-879c-3dd474ab23cc
@token_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTQ4OTg1NDMsImlhdCI6MTc1NDgxMjE0MywidXNlckVtYWlsIjoibWluaGhvY2NvZGUxMTFAZ21haWwuY29tIiwidXNlcklkIjoiZTk5MWQxMTMtNThkYy00MTRjLTg3OWMtM2RkNDc0YWIyM2NjIiwidXNlclJvbGUiOiJhZG1pbiJ9.DcZH5olUzzX9yFSXxIpGI-Tm7WT5fFbqDQn89Jz1YXY
### asd0
@id_user = 530813bf-d772-4b03-bca2-cfe8dbe95f94
@token_user = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTQ5MDc4MzYsImlhdCI6MTc1NDgyMTQzNiwidXNlckVtYWlsIjoiYXNkMUBnbWFpbC5jb20iLCJ1c2VySWQiOiI1MzA4MTNiZi1kNzcyLTRiMDMtYmNhMi1jZmU4ZGJlOTVmOTQiLCJ1c2VyUm9sZSI6InVzZXIifQ.cpgfXV1MG1I6XocsDyLcmWlf5vTmttkYULYEpogMWYo

###
GET {{api}}

###
GET {{api}}/healthz

###
POST {{api}}/auth/register

{
    "email": "asd1@gmail.com",
    "password": "Bruh0!0!"
}

###
POST {{api}}/auth/login

{
    "email": "asd1@gmail.com",
    "password": "Bruh0!0!"
}

###
GET {{api}}/users/all
    ?pageNumber=1
    &perPage=10
    &q=
    &all=true

###
GET {{api}}/auth/me
Authorization: Bearer {{token_user}}

###
GET {{api}}/users/{{id_user}}

###
PATCH {{api}}/users/{{id_user}}
Authorization: Bearer {{token_user}}

{
    "email": "asd1@gmail.com",
    "bio": "dummy"
}

###
PATCH {{api}}/users/{{id_user}}/status
Authorization: Bearer {{token_admin}}

{
    "id": "{{id_user}}",
    "is_active": true
}

###
PATCH {{api}}/users/{{id_user}}/password
Authorization: Bearer {{token_user}}

{
    "old_password": "Bruh0!0!",
    "new_password": "Bruh0!0!"
}

###
DELETE {{api}}/users/{{id_user}}
Authorization: Bearer {{token_admin}}
