x-db-env: &x-db-env
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "user"
  PGDATA: "/var/lib/postgresql/data"

services:
  db:
    container_name: db
    image: postgres:18.1-alpine
    environment:
      <<: *x-db-env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 256Mb
    cpus: 0.25

volumes:
  db_data:
